name: Remove Images

on:
  # schedule:
  #   - cron: "0 0 1 * *"  # Runs at 00:00 UTC on the first day of each month
  workflow_dispatch:

jobs:
  remove-images:
    runs-on: ubuntu-latest
    steps:
      - name: Clone target repository
        run: |
          git clone "https://x-access-token:${{ secrets.IMG_PAT }}@${{ secrets.GH_UPLOAD_REPO }}.git" repo
        env:
          IMG_PAT: ${{ secrets.IMG_PAT }}

      - name: Set up Git in repository
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
        working-directory: repo

      - name: Remove files
        run: |
          find . -mindepth 1 -maxdepth 1 ! -name '.git' ! -name '.gitignore' ! -name 'README.md' -exec rm -rf {} +
        working-directory: repo

      - name: Commit changes
        run: |
          git add .
          git commit -m "Remove image files" || echo "No changes to commit"
        working-directory: repo

      - name: Push changes
        run: |
          git push origin main
        env:
          IMG_PAT: ${{ secrets.IMG_PAT }}
        working-directory: repo
